// copyright Iompa


#include "LogChannels.h"

DEFINE_LOG_CATEGORY(LogProjectW);
DEFINE_LOG_CATEGORY(LogWFunc);

DEFINE_LOG_CATEGORY(LogNetwork);
DEFINE_LOG_CATEGORY(LogSpell);
DEFINE_LOG_CATEGORY(LogCharacter);
DEFINE_LOG_CATEGORY(LogPlayer);
DEFINE_LOG_CATEGORY(LogInventory);
DEFINE_LOG_CATEGORY(LogCombat);
DEFINE_LOG_CATEGORY(LogEnvironment);
